version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookstore
      - JWT_SECRET=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
